

OBJS=  arraylist.o debug.o JSON_checker.o json_more_utils.o json_object.o json_tokener.o json_util.o linkhash.o printbuf.o aux_json.o
APPS= 


LDFLAGS+=
CPPFLAGS+=

include ../global.mk
include $(BUILD_TOOLS_DIR)/Makefile.generic-shared-object	


